### ISSUE TITLE
mitm.bypass() stops working after changing the event name in the handler.

### ISSUE THREAD

**Issue by elbik** [gunnargrosch/failure-lambda#12]
I would like to ask why the event was changed to the _connection_ in this commit [ae590c8f7b73b1eec64ab2460b0987df03d4cddc](https://github.com/gunnargrosch/failure-lambda/pull/11/commits/ae590c8f7b73b1eec64ab2460b0987df03d4cddc) ?

The current change is quite crucial, while it breaks the logic of _usingsocket.bypass()_. When we start relying on the _connection_ event, then it's not possible to bypass the mitm hook and continue the origin request, because the check of bypassed flag in mitm is done on the connect event.
[mitm.connect](https://github.com/moll/node-mitm/blob/master/index.js#L95)

I am looking forward to your response.

**Comment by gunnargrosch** [comment]
Sorry for the late reply. 

Using connect has meant that enabling/disabling the failure mode has been difficult only using the parameter. It has basically meant that you need to refresh the function container (update, redeploy, new cold start, etc) for the enable/disable to take effect. That was the reason to move to connection, since that allowed us to enable/disable denylist simply by changing the parameter.

Do you mean that it's blocking all network connections, not only those in the denylist? The functionality should be to block the hosts in the denylist only.

if (block) { //Should catch the hosts in the denylist
  socket.end()
} else { //Should catch everything else
  socket.bypass()
}

**Comment by elbik** [comment]
Hi, 
I see, the idea is clear, but it blocks all connections and not only supposed one from denylist. 

when we call `socket.bypass()`(behind the scene the method just change the flag `.bypassed` to true) in onConnectionHandler,  then the flag `bypassed` will be never checked/used in [node-mitm](https://github.com/moll/node-mitm/blob/master/index.js#L96) and it leads to blocking all request because the original request is not called anymore.

Or do I miss anything?

**Comment by gunnargrosch** [comment]
Got it. I haven't seen that behavior, so need to run some tests to confirm it. Thanks!

**Comment by gunnargrosch** [comment]
I've confirmed the behavior and switched back to connect for now. Will create a new issue for the problem with enable/disable.
